[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { version = "1.46.1", features = ["full"] }
log = { version = "0.4", features = ["std", "serde"] }
anyhow = { version = "1.0", default-features = false }
